packages:
  - "examples/*"

overrides:
  "@cloudflare/vite-plugin": "catalog:"
  "@cloudflare/workers-types": "catalog:"
  "@tanstack/react-query": "catalog:"
  "@types/node": "catalog:"
  "@types/react": "catalog:"
  "@types/react-dom": "catalog:"
  "@vitejs/plugin-react": "catalog:"
  globals: "catalog:"
  react: "catalog:"
  react-dom: "catalog:"
  "tempo.ts": "catalog:"
  typescript: "catalog:"
  viem: "catalog:"
  vite: "catalog:"
  wagmi: "catalog:"
  wrangler: "catalog:"

catalog:
  "@cloudflare/vite-plugin": ^1.13.18
  "@cloudflare/workers-types": ^4.20251014.0
  "@tanstack/react-query": ^5
  "@types/node": ^24.10.0
  "@types/react": ^19.2.2
  "@types/react-dom": ^19.2.2
  "@vitejs/plugin-react": ^5.1.0
  globals: ^16.5.0
  react: ^19
  react-dom: ^19
  "tempo.ts": ~0.14.0
  typescript: ~5.9.3
  viem: ^2.46.2
  vite: ^7.2.2
  wagmi: ^3.4.4
  wrangler: ^4.50.0
